// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG14dNXJseSL4rvngkWKqnqdgrY_13Lkg',
    appId: '1:5085719278:web:cc049c14a37e0cca0061ff',
    messagingSenderId: '5085719278',
    projectId: 'habit-tracker-93de7',
    authDomain: 'habit-tracker-93de7.firebaseapp.com',
    storageBucket: 'habit-tracker-93de7.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkOE1-K_g_wbV6s1TX33Y8jY92fxc395g',
    appId: '1:5085719278:ios:bf9754f93c3cac850061ff',
    messagingSenderId: '5085719278',
    projectId: 'habit-tracker-93de7',
    storageBucket: 'habit-tracker-93de7.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkOE1-K_g_wbV6s1TX33Y8jY92fxc395g',
    appId: '1:5085719278:ios:bf9754f93c3cac850061ff',
    messagingSenderId: '5085719278',
    projectId: 'habit-tracker-93de7',
    storageBucket: 'habit-tracker-93de7.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb8v4_Q15amYcEMkq8MYdCn-FLMEwCtHU',
    appId: '1:5085719278:android:dc19adf642d3db120061ff',
    messagingSenderId: '5085719278',
    projectId: 'habit-tracker-93de7',
    storageBucket: 'habit-tracker-93de7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG14dNXJseSL4rvngkWKqnqdgrY_13Lkg',
    appId: '1:5085719278:web:f7102722e2e774550061ff',
    messagingSenderId: '5085719278',
    projectId: 'habit-tracker-93de7',
    authDomain: 'habit-tracker-93de7.firebaseapp.com',
    storageBucket: 'habit-tracker-93de7.firebasestorage.app',
  );
}
